apiVersion: v1
kind: Service
metadata:
 name: nginx-01
spec:
 type: NodePort
 ports:
  - name: http
    port: 36999
    nodePort: 36999
  - name: https
    port: 37000
    nodePort: 37000
 selector:
   app: nginx-01