apiVersion: v1
kind: ReplicationController
metadata:
 name: nginx-01
spec:
 replicas: 1
 selector:
  app: nginx-01
 template:
  metadata:
   labels:
    app: nginx-01
  spec:
   containers:
   - name: nginx-01
     image: ubuntu
     ports:
     - containerPort: 8080
     command: ["sleep","111111"]
